# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('exID', models.AutoField(primary_key=True, serialize=False)),
                ('orderNum', models.IntegerField()),
                ('purpose', models.CharField(max_length=240)),
                ('main', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('alt1', models.CharField(max_length=30)),
                ('alt2', models.CharField(max_length=30)),
                ('alt3', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('bodyWeight', models.IntegerField()),
                ('squatMax', models.IntegerField(null=True)),
                ('benchMax', models.IntegerField(null=True)),
                ('deadliftMax', models.IntegerField(null=True)),
                ('snatchMax', models.IntegerField(null=True)),
                ('cleanMax', models.IntegerField(null=True)),
                ('goals', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='UserDoesExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.IntegerField()),
                ('date', models.DateField()),
                ('exMax', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='was.Exercises')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='was.User')),
            ],
        ),
    ]
