# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('was', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userLevel',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('novice', 'Novice'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=12),
        ),
    ]
