# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('was', '0004_remove_user_goals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdoesexercise',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='userdoesexercise',
            name='usr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cleanMax',
        ),
        migrations.RemoveField(
            model_name='user',
            name='snatchMax',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userLevel',
        ),
        migrations.DeleteModel(
            name='Exercises',
        ),
        migrations.DeleteModel(
            name='UserDoesExercise',
        ),
    ]
